on:
  workflow_call:
    # inputs:
    #   environment:
    #     required: true
    #     type: string

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.event.inputs.environment }}

      - name: report
        shell: bash
        run: |
          pwd
          ls -la

      - name: write-file
        shell: bash
        run: |
          echo "${{ vars.GREETING }}" > env.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: replace-${{ github.event.inputs.environment }}
          path: |
            ./
